
name: kommod
title: kommod
version: '0.0.1'
summary: The all in one project debuger and analyzer
description: This tool is for two specific propuses the first on is analyzing your projects based on a varity of different tools as well as issues. The second one is about helping you debug your projects for common issues and difficulties.
grade: stable
confinement: classic
base: core18

website: https://github.com/BenCoepp/kommod
issues: https://github.com/BenCoepp/kommod/issues
license: MIT

architectures:
  - build-on: amd64

apps:
  kommod:
    command:
      java -jar -Duser.home=$SNAP_USER_DATA $SNAP/jar/kommod-0.0.1-SNAPSHOT.jar
    plugs: [ home, network, network-bind, system-files]

parts:
  kommod:
    source: https://github.com/BenCoepp/kommod.git
    source-tag: main
    source-type: git
    plugin: maven
    stage:
      - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      - -etc/java-11-openjdk/security/blacklisted.certs lint-snap-v2_external_symlinks
