
name: kommod
title: kommod
version: '0.0.1'
summary: The all in one project analyzer
description: |
  This tool is mainly for two things, analyzing your projects and auditing them. Please note that at this time this tool is still under development...
grade: stable
confinement: strict
base: core18

website: https://github.com/BenCoepp/kommod
issues: https://github.com/BenCoepp/kommod/issues
license: MIT

architectures:
  - build-on: amd64

apps:
  kommod:
    command:
      java -jar -Duser.home=$SNAP_USER_DATA $SNAP/jar/kommod-0.0.1-SNAPSHOT.jar
    plugs: [ home, network, network-bind, system-files]

parts:
  kommod:
    source: https://github.com/BenCoepp/kommod.git
    source-tag: main
    source-type: git
    plugin: maven
    stage:
      - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      - -etc/java-11-openjdk/security/blacklisted.certs lint-snap-v2_external_symlinks
